// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type CausalRelation struct {
	ID         string `json:"id"`
	CauseType  string `json:"causeType"`
	FromEntity string `json:"fromEntity"`
	ToEntity   string `json:"toEntity"`
}

type Mutation struct {
}

type Query struct {
}

type Substance struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Kind      string           `json:"kind"`
	Essence   string           `json:"essence"`
	CreatedAt string           `json:"createdAt"`
	Causes    []CausalRelation `json:"causes"`
}
