version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ontology_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: ontology_pgadmin
    restart: always
    env_file:
      - ../.env
    ports:
      - "5050:80"
    depends_on:
      - db

  ontology-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ontology_service
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata: